### ISSUE TITLE
Add export to CSV

### ISSUE THREAD

**Issue by ghost** [ExCiteS/geokey-export#12]
@prickles @michalis-vitos @julia-altenbuchner @EmpressNaledi - ideas on how the exported CSV should look like (e.g. how many-to-many relations are handled - comments, media) are welcome.

**Comment by michalis-vitos** [comment]
Hi Julius,

Can you please provide some basic examples of projects so that we can better understand the challenges?

I can suggest you two different approaches based on the following very simple scenario. Imagine that you have a project about Universities where you have the following tables:

**University**

| id | name | Address |
|--------|--------|--------|
| 1 | UCL               |    Gower Street    |
| 2 | Imperial College    | South of Hyde Park!|


**Supervisor**

| id | Name | University |
|--------|--------|--------|
| 1| Muki Haklay| 1|
| 2| Claire Ellul | 1|

**Student**

| id | Name | University | Supervisor |
|--------|--------|--------|--------|
| 1| Michalis Vitos| 1|1|
| 2| Julia Altenbuchner | 1|2|

As you can see there are the following rellationships <br />
University one-to-many Supervisor<br />
University one-to-many Student<br />
Supervisors one-to-many Student<br />

Of course, this is a very simplified example!

Now in terms of CSV, depending on how much you want to [normalise](https://en.wikipedia.org/wiki/Database_normalization) the output, you can have:

### Without normalisation
The first approach would be to avoid normalisation and output everything into one big denormalised CSV:

| uni_id | uni_name | uni_address | sup_id | sup_name | stu_id | stu_name |
|--------|--------|--------|--------|--------|--------|--------|
| 1 | UCL       |	Gower Street	| 1| Muki Haklay| 1|Michalis Vitos|
| 1 | UCL       |	Gower Street	| 2| Claire Ellul | 2|Julia Altenbuchner|
| 2 | Imperial College| South of Hyde Park!|	|	|	|

**Pros:** One file as an output, which would be easier for not tech savvy people to use.
**Cons:** This approach will lead to a lot of data duplication in the file and will also leave many rows with empty columns. Depending on the number of tables and columns, this might create a very hard to understand file.

### With normalisation

In this case, you create a separate CSV file for each of the tables in your database. Therefore, you will end up having the files universities.csv, supervisors.csv and studends.csv. The many-to-many relationships are harder to export without duplication and might require to also export files that represent the relationship e.g. SupervisorsToStudends.csv etc.

**Pros:** Each file will contain only relevant data, so there would be no duplication.
**Cons:** Harder to use the output in Excel. You can create relationships and link different tables on Excel, but I am not sure how many users know how to do that.

**Comment by claireellul** [comment]
Hi Michalis and all

Nice example – except you also have to contend with the many:many student/supervisor relationship.

Not seen the rest of this discussion for some reason, but I would suggest that the first way to build this is to have the non-normalised approach as this means that anyone can use the CSV file on a map.  We can add normalised output if required but that kind of implies that the data will be stored in another database as it isn’t easy to use normalised CSV files in GIS software ….  (yes, GIS is useless!)….

Not sure if I’ve understood the discussion … apologies if not

Cheers

Claire

**Comment by juliusosokinas** [comment]
@sliob files can be archived and downloaded as one ZIP. I've made a nice in-memory compression yesterday for the Sapelli guys, you can have a look at the [source code](https://github.com/ExCiteS/geokey-sapelli/blob/master/geokey_sapelli/views.py#L425) for an example.
